### ISSUE TITLE
安装执行出错exit status 2

### ISSUE THREAD

**Issue by ohlinux** [polaris1119/autogo#1]
Linux环境下安装完autogo之后，配置好json

[
    {
        "name": "todolist",
        "root": "/root/Dropbox/code/html5/to-do-list/src/todolist",
        "depends": []
    }
]

执行./bin/autogo，报错

2012/12/19 15:37:23 exit status 2

下面是我的程序目录结构：注意一点就是我的执行位置必需在　/root/Dropbox/code/html5/to-do-list/
![marathon21](https://f.cloud.github.com/assets/1715979/21456/c4bdbf04-49af-11e2-95af-a40a7489da5b.png)

**Comment by ohlinux** [comment]
发现一个问题　首先json是错误的　  "root": "/root/Dropbox/code/html5/to-do-list/src/todolist",　是项目根目录　  "root": "/root/Dropbox/code/html5/to-do-list",

**Comment by polaris1119** [comment]
调试发现，linux下执行make调用了系统默认的make
谢谢反馈，已经修复
看来各个系统都得试试。
我只试了windows系统
